name: CI Workflow

on:
  push:
    branches:
      - main
      - "*"
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'  # Or the version you prefer

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q

    - name: Upload test results (optional)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-logs
        path: ./test-results/
